import { Injectable } from "@angular/core";
import { Observable, of } from "rxjs";
import { delay, mergeMap, materialize, dematerialize } from "rxjs/operators";
import {
  HttpRequest,
  HttpResponse,
  HttpHandler,
  HttpEvent,
  HttpInterceptor,
  HTTP_INTERCEPTORS
} from "@angular/common/http";

@Injectable()
export class FakeServerInterceptor implements HttpInterceptor {
  constructor() 
  {}
  //simulate the server with an observable
  intercept(
    request: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {
    return (
      of(null)
        .pipe(
          mergeMap(() => {
            // get categories legacy
            if (
              request.url.endsWith("/categories") &&
              request.method === "GET"
            ) {
              const categories = [
                {
                  id: "74effa1e-2fce-e811-af11-00155daaf652",
                  guideId: "72effa1e-2fce-e811-af11-00155daaf652",
                  sequence: 1,
                  description: "Cooler",
                  isReadOnly: false,
                  version: "AAAAACL/xEc=",
                  productCount: 0
                },
                {
                  id: "73effa1e-2fce-e811-af11-00155daaf652",
                  guideId: "72effa1e-2fce-e811-af11-00155daaf652",
                  sequence: 2,
                  description: "Freeze",
                  isReadOnly: false,
                  version: "AAAAACL/xEY=",
                  productCount: 0
                },
                {
                  id: "76effa1e-2fce-e811-af11-00155daaf652",
                  guideId: "72effa1e-2fce-e811-af11-00155daaf652",
                  sequence: 3,
                  description: "Dry Storage",
                  isReadOnly: false,
                  version: "AAAAACL/xEk=",
                  productCount: 0
                },
                {
                  id: "77effa1e-2fce-e811-af11-00155daaf652",
                  guideId: "72effa1e-2fce-e811-af11-00155daaf652",
                  sequence: 4,
                  description: "Non-Food",
                  isReadOnly: false,
                  version: "AAAAACL/xEo=",
                  productCount: 0
                },
                {
                  id: "75effa1e-2fce-e811-af11-00155daaf652",
                  guideId: "72effa1e-2fce-e811-af11-00155daaf652",
                  sequence: 5,
                  description: "Uncategorized",
                  isReadOnly: true,
                  version: "AAAAACL/xEg=",
                  productCount: 12
                }
              ];
              return of(new HttpResponse({ status: 200, body: categories }));
            }

            // get guide detail legacy
            if (
              request.url.endsWith("/guide-detail-legacy") &&
              request.method === "GET"
            ) {
              const guideDetailLegacy = [
                {
                  lineNumber: 1,
                  par: null,
                  pricebook: "6235",
                  lastOrderDate: null,
                  lastCaseOrderQuantity: null,
                  lastEachOrderQuantity: null,
                  averageOrderQuantity: null,
                  categoryNumber: null,
                  categoryId: "75effa1e-2fce-e811-af11-00155daaf652",
                  categoryName: "Uncategorized",
                  customProductNumber: null,
                  isDeactivated: false,
                  isSuspended: false,
                  product: {
                    id: "0765cda6-34a1-4a17-b2f0-a53400190e8d",
                    number: "120892",
                    name: "FLATBREAD 12X5 RUSTIC OVAL",
                    description:
                      "RUSTIC OVAL FLATBREAD WITH HAND MADE APPEARANCE.",
                    brand: "RICH",
                    classNumber: " 62",
                    fsaBranded: false,
                    breakCase: false,
                    pack: 48,
                    size: "4.8Z",
                    packSize: "48/4.8Z",
                    weight: 16.44,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/120892",
                    authorized: true,
                    deactivated: false,
                    suspended: false,
                    orderable: true,
                    orderableMessage: null,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Freeze", display: "Freeze" }],
                    pricing: {
                      productId: "0765cda6-34a1-4a17-b2f0-a53400190e8d",
                      casePrice: 47.0,
                      priceCode: "W",
                      priceCodeDescription: "W - Zone Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 108,
                      specialPriceCode: null
                    },
                    salesData: {
                      id: "00000000-0000-0000-0000-000000000000",
                      number: null,
                      pricing: {
                        caseCost: 45.0,
                        eachCost: null,
                        caseGrossProfit: 1.05,
                        caseGrossProfitPercent: 0.0794237138441156988297637448,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: false,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 44.69,
                        starCasePrice3: 48.76,
                        starCasePrice5: 55.39,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 48.2374,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: {
                        code: "I",
                        caseAmount: 0.63,
                        eachAmount: null
                      },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  lineNumber: 2,
                  par: null,
                  pricebook: "2756",
                  lastOrderDate: null,
                  lastCaseOrderQuantity: null,
                  lastEachOrderQuantity: null,
                  averageOrderQuantity: null,
                  categoryNumber: null,
                  categoryId: "75effa1e-2fce-e811-af11-00155daaf652",
                  categoryName: "Uncategorized",
                  customProductNumber: null,
                  isDeactivated: false,
                  isSuspended: false,
                  product: {
                    id: "ca9ae8d0-fe76-e811-80f0-0050568e5b90",
                    number: "840533",
                    name: "PASTA FUSILLI BUCATI",
                    description:
                      'THIN CORKSCREW-SHAPED RIDGED PASTA CUT 1.5"-2.0" X 0.30" DIAMETER, EXTRUDED THROUGH A TEFLON DIE. PRODUCT MADE FROM 100% DURUM SEMOLINA. NO EGG. BEAUTIFUL AMBER COLOR AND HIGHEST QUALITY GLUTEN STRENGTH FOR AL DENTE EXPERIENCE. OU KOSHER PAREVE. BRC CERT PRODUCTION FCLTY',
                    brand: "DELLA VITA",
                    classNumber: " 27",
                    fsaBranded: true,
                    breakCase: false,
                    pack: 2,
                    size: "5#",
                    packSize: "2/5#",
                    weight: 10.86,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/840533",
                    authorized: true,
                    deactivated: false,
                    suspended: false,
                    orderable: true,
                    orderableMessage: null,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Dry", display: "Dry" }],
                    pricing: {
                      productId: "ca9ae8d0-fe76-e811-80f0-0050568e5b90",
                      casePrice: 15.84,
                      priceCode: "W",
                      priceCodeDescription: "W - Zone Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 169,
                      specialPriceCode: null
                    },
                    salesData: {
                      id: "00000000-0000-0000-0000-000000000000",
                      number: null,
                      pricing: {
                        caseCost: 14.39,
                        eachCost: null,
                        caseGrossProfit: 0.21,
                        caseGrossProfitPercent: 0.0742367601246105919003115265,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: false,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 15.97,
                        starCasePrice3: 18.05,
                        starCasePrice5: 19.6,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 18.6289,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: {
                        code: "I",
                        caseAmount: 0.44,
                        eachAmount: null
                      },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  lineNumber: 3,
                  par: null,
                  pricebook: "4190",
                  lastOrderDate: null,
                  lastCaseOrderQuantity: null,
                  lastEachOrderQuantity: null,
                  averageOrderQuantity: null,
                  categoryNumber: null,
                  categoryId: "75effa1e-2fce-e811-af11-00155daaf652",
                  categoryName: "Uncategorized",
                  customProductNumber: null,
                  isDeactivated: false,
                  isSuspended: false,
                  product: {
                    id: "f6954241-7f87-e811-80f0-0050568e5b90",
                    number: "887489",
                    name: "SPREAD AIOLI LEMON",
                    description: "LEMON FLAVORED AOILI SPREAD",
                    brand: "LITEHOUSE",
                    classNumber: " 41",
                    fsaBranded: false,
                    breakCase: false,
                    pack: 6,
                    size: "32Z",
                    packSize: "6/32Z",
                    weight: 13.25,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: null,
                    authorized: true,
                    deactivated: false,
                    suspended: false,
                    orderable: true,
                    orderableMessage: null,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Chill", display: "Chill" }],
                    pricing: {
                      productId: "f6954241-7f87-e811-80f0-0050568e5b90",
                      casePrice: 33.21,
                      priceCode: "W",
                      priceCodeDescription: "W - Zone Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 4,
                      specialPriceCode: null
                    },
                    salesData: {
                      id: "00000000-0000-0000-0000-000000000000",
                      number: null,
                      pricing: {
                        caseCost: 30.6,
                        eachCost: null,
                        caseGrossProfit: 1.32,
                        caseGrossProfitPercent: 0.0594248545018829168093118795,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: false,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 30.22,
                        starCasePrice3: 31.3,
                        starCasePrice5: 35.08,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 30.8915,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: {
                        code: "I",
                        caseAmount: 0.4,
                        eachAmount: null
                      },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  lineNumber: 4,
                  par: null,
                  pricebook: "5510",
                  lastOrderDate: null,
                  lastCaseOrderQuantity: null,
                  lastEachOrderQuantity: null,
                  averageOrderQuantity: null,
                  categoryNumber: null,
                  categoryId: "75effa1e-2fce-e811-af11-00155daaf652",
                  categoryName: "Uncategorized",
                  customProductNumber: null,
                  isDeactivated: false,
                  isSuspended: false,
                  product: {
                    id: "472b96e4-11ab-47b1-bf99-50ddcf666249",
                    number: "186619",
                    name: "BEEF POT ROAST CHOICE COOKED",
                    description:
                      "USDA CHOICE, BEEF CHUCK SHOULDER CLOD. MED-WELL COOK. DINNER STYLE POT ROAST 20% MARINATION. SLOW ROASTED 14-16 HOURS. SEASONED WITH BLACK PEPPER, ONIONS AND CARROTS. WET PACK.",
                    brand: "1890F",
                    classNumber: " 55",
                    fsaBranded: true,
                    breakCase: false,
                    pack: 1,
                    size: "10#A",
                    packSize: "1/10#A",
                    weight: 11.0,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: true,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/186619",
                    authorized: true,
                    deactivated: false,
                    suspended: false,
                    orderable: true,
                    orderableMessage: null,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Freeze", display: "Freeze" }],
                    pricing: {
                      productId: "472b96e4-11ab-47b1-bf99-50ddcf666249",
                      casePrice: 8.13,
                      priceCode: "W",
                      priceCodeDescription: "W - Zone Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 163,
                      specialPriceCode: null
                    },
                    salesData: {
                      id: "00000000-0000-0000-0000-000000000000",
                      number: null,
                      pricing: {
                        caseCost: 8.77,
                        eachCost: null,
                        caseGrossProfit: 0.26,
                        caseGrossProfitPercent: 0.0501754385964912280701754386,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: false,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 6.28,
                        starCasePrice3: 7.3,
                        starCasePrice5: 8.38,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 6.77,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: { code: "I", caseAmount: 0.0, eachAmount: null },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  lineNumber: 5,
                  par: null,
                  pricebook: "4180",
                  lastOrderDate: null,
                  lastCaseOrderQuantity: null,
                  lastEachOrderQuantity: null,
                  averageOrderQuantity: null,
                  categoryNumber: null,
                  categoryId: "75effa1e-2fce-e811-af11-00155daaf652",
                  categoryName: "Uncategorized",
                  customProductNumber: null,
                  isDeactivated: false,
                  isSuspended: false,
                  product: {
                    id: "1fdec718-63f9-43b1-825a-7ea1376f0c7e",
                    number: "325342",
                    name: "CHEESE MOZZARELLA FRESH BURRATA 4Z WATER",
                    description:
                      "THERE ARE 4 / 4 OZ BALLS PER TUB. THIS RARE ITALIAN DELICACY IS SILKY ON THE OUTSIDE AND CREAMY ON THE INSIDE. BURRATA BOASTS A RICHY SWEET, MILKY FLAVOR THAT IS SURE TO PLEASE THE PALATE. PACKAGED IN WATER FOR AN EXTENDED SHELF LIFE.",
                    brand: "BELGIOIOSO",
                    classNumber: " 41",
                    fsaBranded: false,
                    breakCase: true,
                    pack: 6,
                    size: "1#",
                    packSize: "6/1#",
                    weight: 10.52,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: null,
                    authorized: true,
                    deactivated: false,
                    suspended: false,
                    orderable: true,
                    orderableMessage: null,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Chill", display: "Chill" }],
                    pricing: {
                      productId: "1fdec718-63f9-43b1-825a-7ea1376f0c7e",
                      casePrice: 48.48,
                      priceCode: "W",
                      priceCodeDescription: "W - Zone Override",
                      eachPrice: 8.8,
                      eachPriceCode: "W",
                      eachPriceCodeDescription: "W - Zone Override",
                      quantityOnHand: 16,
                      specialPriceCode: null
                    },
                    salesData: {
                      id: "00000000-0000-0000-0000-000000000000",
                      number: null,
                      pricing: {
                        caseCost: 44.7,
                        eachCost: 8.1404,
                        caseGrossProfit: 4.55,
                        caseGrossProfitPercent: 0.0498111510791366906474820144,
                        eachGrossProfit: 0.5196,
                        eachGrossProfitPercent: 0.0494358974358974358974358974,
                        isCaseOverride: false,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 44.33,
                        starCasePrice3: 48.4,
                        starCasePrice5: 52.38,
                        starEachPrice1: 6.15,
                        starEachPrice3: 6.66,
                        starEachPrice5: 9.0,
                        caseOverrideThreshold: 44.9314,
                        eachOverrideThreshold: 8.8219,
                        flyerPrices: []
                      },
                      freight: {
                        code: "I",
                        caseAmount: 0.29,
                        eachAmount: 0.08
                      },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  lineNumber: 6,
                  par: null,
                  pricebook: "5510",
                  lastOrderDate: null,
                  lastCaseOrderQuantity: null,
                  lastEachOrderQuantity: null,
                  averageOrderQuantity: null,
                  categoryNumber: null,
                  categoryId: "75effa1e-2fce-e811-af11-00155daaf652",
                  categoryName: "Uncategorized",
                  customProductNumber: null,
                  isDeactivated: false,
                  isSuspended: false,
                  product: {
                    id: "2f8d349f-5465-4a7a-9aa4-cc942e66b02c",
                    number: "328176",
                    name:
                      "BEEF PATTY 2/1 HOMESTYLE 80%  CHOPD  INDIVIDUALLY QUICK FROZEN",
                    description:
                      'HOMESTYLE SHAPED, CHOPPED, 80% LEAN BEEF STEAK. INDIVIDUALLY QUICK FROZEN F/EASY USE. COOK FROM FROZEN. IDEAL F/JUICY BURGERS, CHICKEN FRIED STEAK, SALISBURY & SWISS STEAK. MATCHES ROCHESTER "CLOUD" PATTY, ROLLED. FSA# 174114 "CLOUD" PATTY, FSA# 174114',
                    brand: "1890F",
                    classNumber: " 55",
                    fsaBranded: true,
                    breakCase: false,
                    pack: 1,
                    size: "15#",
                    packSize: "1/15#",
                    weight: 17.0,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/328176",
                    authorized: true,
                    deactivated: false,
                    suspended: false,
                    orderable: true,
                    orderableMessage: null,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Freeze", display: "Freeze" }],
                    pricing: {
                      productId: "2f8d349f-5465-4a7a-9aa4-cc942e66b02c",
                      casePrice: 55.68,
                      priceCode: "W",
                      priceCodeDescription: "W - Zone Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 515,
                      specialPriceCode: null
                    },
                    salesData: {
                      id: "00000000-0000-0000-0000-000000000000",
                      number: null,
                      pricing: {
                        caseCost: 52.62,
                        eachCost: null,
                        caseGrossProfit: 6.62,
                        caseGrossProfitPercent: 0.0693962848297213622291021672,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: false,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 55.66,
                        starCasePrice3: 60.04,
                        starCasePrice5: 61.36,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 50.062,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: {
                        code: "I",
                        caseAmount: 0.48,
                        eachAmount: null
                      },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  lineNumber: 7,
                  par: null,
                  pricebook: "3850",
                  lastOrderDate: null,
                  lastCaseOrderQuantity: null,
                  lastEachOrderQuantity: null,
                  averageOrderQuantity: null,
                  categoryNumber: null,
                  categoryId: "75effa1e-2fce-e811-af11-00155daaf652",
                  categoryName: "Uncategorized",
                  customProductNumber: null,
                  isDeactivated: false,
                  isSuspended: false,
                  product: {
                    id: "7b777ea0-3f4c-4fc5-af3b-a15ef9f90872",
                    number: "276852",
                    name: "SCALLOPS SEA USA NATURAL UNDER/10 ALL NATURAL",
                    description:
                      "US SCALLOPS CAUGHT OFF THE EAST COAST. LESS THAN 10 SCALLOPS PER POUND. US SCALLOP FISHERY IS VERY WELL MANAGED F/SUSTAINABILITY. GREAT F/SUSHI OR CARMELIZING. NO WATER OR CHEMICALS ADDED.",
                    brand: "FLY FLAGPR",
                    classNumber: " 38",
                    fsaBranded: true,
                    breakCase: true,
                    pack: 2,
                    size: "5#",
                    packSize: "2/5#",
                    weight: 11.0,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/276852",
                    authorized: true,
                    deactivated: false,
                    suspended: false,
                    orderable: true,
                    orderableMessage: null,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Freeze", display: "Freeze" }],
                    pricing: {
                      productId: "7b777ea0-3f4c-4fc5-af3b-a15ef9f90872",
                      casePrice: 155.38,
                      priceCode: "W",
                      priceCodeDescription: "W - Zone Override",
                      eachPrice: 88.61,
                      eachPriceCode: "W",
                      eachPriceCodeDescription: "W - Zone Override",
                      quantityOnHand: 85,
                      specialPriceCode: null
                    },
                    salesData: {
                      id: "00000000-0000-0000-0000-000000000000",
                      number: null,
                      pricing: {
                        caseCost: 150.9,
                        eachCost: 77.5789,
                        caseGrossProfit: 15.19,
                        caseGrossProfitPercent: 0.0549096264560182085955281832,
                        eachGrossProfit: 3.8911,
                        eachGrossProfitPercent: 0.0549408472204554127973540262,
                        isCaseOverride: false,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 150.33,
                        starCasePrice3: 155.18,
                        starCasePrice5: 160.63,
                        starEachPrice1: 75.58,
                        starEachPrice3: 80.4,
                        starEachPrice5: 85.16,
                        caseOverrideThreshold: 150.186,
                        eachOverrideThreshold: 75.093,
                        flyerPrices: []
                      },
                      freight: {
                        code: "I",
                        caseAmount: 0.44,
                        eachAmount: 0.24
                      },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  lineNumber: 8,
                  par: null,
                  pricebook: "5575",
                  lastOrderDate: null,
                  lastCaseOrderQuantity: null,
                  lastEachOrderQuantity: null,
                  averageOrderQuantity: null,
                  categoryNumber: null,
                  categoryId: "75effa1e-2fce-e811-af11-00155daaf652",
                  categoryName: "Uncategorized",
                  customProductNumber: null,
                  isDeactivated: false,
                  isSuspended: false,
                  product: {
                    id: "6e0bebba-b2a9-4638-b297-f8137349b786",
                    number: "574020",
                    name: "CHICKEN DRUMSTICK COOKED FAST FINISH",
                    description:
                      "FULLY COOKED DRUMSTICKS WITH FAST FINISH COATING. 40-80 PIECES PER CASE WITH AVERAGE 53 DRUMSTICKS.",
                    brand: "TYSON",
                    classNumber: " 55",
                    fsaBranded: false,
                    breakCase: false,
                    pack: 1,
                    size: "10#",
                    packSize: "1/10#",
                    weight: 10.63,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/574020",
                    authorized: true,
                    deactivated: false,
                    suspended: false,
                    orderable: true,
                    orderableMessage: null,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Freeze", display: "Freeze" }],
                    pricing: {
                      productId: "6e0bebba-b2a9-4638-b297-f8137349b786",
                      casePrice: 28.49,
                      priceCode: "W",
                      priceCodeDescription: "W - Zone Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 89,
                      specialPriceCode: null
                    },
                    salesData: {
                      id: "00000000-0000-0000-0000-000000000000",
                      number: null,
                      pricing: {
                        caseCost: 25.02,
                        eachCost: null,
                        caseGrossProfit: 1.19,
                        caseGrossProfitPercent: 0.0694242547978766843609636586,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: false,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 25.54,
                        starCasePrice3: 27.02,
                        starCasePrice5: 29.41,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 26.2964,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: {
                        code: "I",
                        caseAmount: 0.3,
                        eachAmount: null
                      },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  lineNumber: 9,
                  par: null,
                  pricebook: "5550",
                  lastOrderDate: null,
                  lastCaseOrderQuantity: null,
                  lastEachOrderQuantity: null,
                  averageOrderQuantity: null,
                  categoryNumber: null,
                  categoryId: "75effa1e-2fce-e811-af11-00155daaf652",
                  categoryName: "Uncategorized",
                  customProductNumber: null,
                  isDeactivated: false,
                  isSuspended: false,
                  product: {
                    id: "666b9fe8-8382-4897-843e-b2e4463dfc59",
                    number: "749559",
                    name: "PORK LOIN CENTER CUT MARINATED BONELESS HALF",
                    description:
                      "BONELESS PORK LOIN, CENTER CUT. SEASONED WITH A 15% SOLUTION OF WATER AND SEA SALT. STRAP OFF, 4/3.5-5.5 LBS PER CASE.",
                    brand: "CALUMET",
                    classNumber: " 55",
                    fsaBranded: false,
                    breakCase: false,
                    pack: 4,
                    size: "4.5#A",
                    packSize: "4/4.5#A",
                    weight: 20.0,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: true,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/749559",
                    authorized: true,
                    deactivated: false,
                    suspended: false,
                    orderable: true,
                    orderableMessage: null,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Freeze", display: "Freeze" }],
                    pricing: {
                      productId: "666b9fe8-8382-4897-843e-b2e4463dfc59",
                      casePrice: 4.74,
                      priceCode: "W",
                      priceCodeDescription: "W - Zone Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 186,
                      specialPriceCode: null
                    },
                    salesData: {
                      id: "00000000-0000-0000-0000-000000000000",
                      number: null,
                      pricing: {
                        caseCost: 3.52,
                        eachCost: null,
                        caseGrossProfit: 0.47,
                        caseGrossProfitPercent: 0.0493430656934306569343065693,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: false,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 3.46,
                        starCasePrice3: 4.47,
                        starCasePrice5: 5.47,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 5.546,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: {
                        code: "I",
                        caseAmount: 0.12,
                        eachAmount: null
                      },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  lineNumber: 10,
                  par: null,
                  pricebook: "5550",
                  lastOrderDate: null,
                  lastCaseOrderQuantity: null,
                  lastEachOrderQuantity: null,
                  averageOrderQuantity: null,
                  categoryNumber: null,
                  categoryId: "75effa1e-2fce-e811-af11-00155daaf652",
                  categoryName: "Uncategorized",
                  customProductNumber: null,
                  isDeactivated: false,
                  isSuspended: false,
                  product: {
                    id: "a3cf20e5-68db-4a95-86d6-b3df7b69aac1",
                    number: "648774",
                    name: "PORK OSSO BUCO COOKED",
                    description:
                      "FULLY COOKED HIND SHANKS, WITH NO SEASONING. READY TO ADD YOUR FAVORITE SAUCE. HEAT AND SERVE. BONE IN. EACH 3 POUNDS BAG HAS 2 PIECES.",
                    brand: "FARMLAND",
                    classNumber: " 55",
                    fsaBranded: false,
                    breakCase: false,
                    pack: 6,
                    size: "3#",
                    packSize: "6/3#",
                    weight: 19.1,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/648774",
                    authorized: true,
                    deactivated: false,
                    suspended: false,
                    orderable: true,
                    orderableMessage: null,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Freeze", display: "Freeze" }],
                    pricing: {
                      productId: "a3cf20e5-68db-4a95-86d6-b3df7b69aac1",
                      casePrice: 70.67,
                      priceCode: "W",
                      priceCodeDescription: "W - Zone Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 26,
                      specialPriceCode: null
                    },
                    salesData: {
                      id: "00000000-0000-0000-0000-000000000000",
                      number: null,
                      pricing: {
                        caseCost: 68.46,
                        eachCost: null,
                        caseGrossProfit: 5.71,
                        caseGrossProfitPercent: 0.0596024826363233338259199054,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: false,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 68.28,
                        starCasePrice3: 72.56,
                        starCasePrice5: 75.81,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 68.9566,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: { code: "I", caseAmount: 0.6, eachAmount: null },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  lineNumber: 11,
                  par: null,
                  pricebook: "3850",
                  lastOrderDate: null,
                  lastCaseOrderQuantity: null,
                  lastEachOrderQuantity: null,
                  averageOrderQuantity: null,
                  categoryNumber: null,
                  categoryId: "75effa1e-2fce-e811-af11-00155daaf652",
                  categoryName: "Uncategorized",
                  customProductNumber: null,
                  isDeactivated: false,
                  isSuspended: false,
                  product: {
                    id: "76251e00-e693-e711-80da-0050568e5b90",
                    number: "741746",
                    name: "SALMON MSC SOCKEYE FILLET 1-3 POUND SKIN ON",
                    description:
                      "WILD SALMON SOCKEYE FILLET, 1-3 LBS, SKIN ON, BONELESS. PRODUCT OF USA. ASMI. CRYOVACED PACKAGING. MSC-C-50140",
                    brand: "FLY FLAGPR",
                    classNumber: " 38",
                    fsaBranded: true,
                    breakCase: false,
                    pack: 1,
                    size: "25#",
                    packSize: "1/25#",
                    weight: 27.0,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/741746",
                    authorized: true,
                    deactivated: false,
                    suspended: false,
                    orderable: true,
                    orderableMessage: null,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Freeze", display: "Freeze" }],
                    pricing: {
                      productId: "76251e00-e693-e711-80da-0050568e5b90",
                      casePrice: 280.44,
                      priceCode: "W",
                      priceCodeDescription: "W - Zone Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 156,
                      specialPriceCode: null
                    },
                    salesData: {
                      id: "00000000-0000-0000-0000-000000000000",
                      number: null,
                      pricing: {
                        caseCost: 277.9,
                        eachCost: null,
                        caseGrossProfit: 25.84,
                        caseGrossProfitPercent: 0.069813140446051838456901748,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: false,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 245.75,
                        starCasePrice3: 255.32,
                        starCasePrice5: 275.96,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 250.602,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: { code: "I", caseAmount: 0.8, eachAmount: null },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  lineNumber: 12,
                  par: null,
                  pricebook: "3850",
                  lastOrderDate: null,
                  lastCaseOrderQuantity: null,
                  lastEachOrderQuantity: null,
                  averageOrderQuantity: null,
                  categoryNumber: null,
                  categoryId: "75effa1e-2fce-e811-af11-00155daaf652",
                  categoryName: "Uncategorized",
                  customProductNumber: null,
                  isDeactivated: false,
                  isSuspended: false,
                  product: {
                    id: "fcf56cb1-2782-4784-a8fd-46ac333d87fc",
                    number: "122543",
                    name: "CLAMS STEAMERS 17/22 COUNT",
                    description:
                      "FARM RAISED, SAND FREE, 17 TO 22 PER POUND. VACUUM PACKED HARD SHELL CLAMS. PRODUCT OF CHINA, THAILAND OR VIETNAM. CONTAINS SHELLFISH.",
                    brand: "FLY FLAGPR",
                    classNumber: " 38",
                    fsaBranded: true,
                    breakCase: false,
                    pack: 10,
                    size: "1#",
                    packSize: "10/1#",
                    weight: 11.0,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/122543",
                    authorized: true,
                    deactivated: false,
                    suspended: false,
                    orderable: true,
                    orderableMessage: null,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Freeze", display: "Freeze" }],
                    pricing: {
                      productId: "fcf56cb1-2782-4784-a8fd-46ac333d87fc",
                      casePrice: 36.87,
                      priceCode: "W",
                      priceCodeDescription: "W - Zone Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 470,
                      specialPriceCode: null
                    },
                    salesData: {
                      id: "00000000-0000-0000-0000-000000000000",
                      number: null,
                      pricing: {
                        caseCost: 35.81,
                        eachCost: null,
                        caseGrossProfit: 4.06,
                        caseGrossProfitPercent: 0.0603454384410983170947741364,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: false,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 35.71,
                        starCasePrice3: 40.77,
                        starCasePrice5: 45.78,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 44.81,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: { code: "I", caseAmount: 0.0, eachAmount: null },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                }
              ];
              return of(
                new HttpResponse({ status: 200, body: guideDetailLegacy })
              );
            }

            // get order guide legacy
            if (
              request.url.endsWith("/guide-legacy") &&
              request.method === "GET"
            ) {
              const guideLegacy = [
                {
                  id: "72effa1e-2fce-e811-af11-00155daaf652",
                  number: null,
                  type: "Custom",
                  lineItems: 12,
                  owner: "Joe Smith",
                  created: null,
                  modified: "2018-10-12T15:01:30.051813Z",
                  modifiedBy: "Joe Smith",
                  warehouse: null,
                  priority: null,
                  account: {
                    id: "fe2e733a-0906-416c-bb64-eecab0e6dcb3",
                    name: "Joe's Tavern",
                    number: "5558219"
                  },
                  name: "Fall Menu",
                  locked: false,
                  canUnlock: true,
                  private: false,
                  version: "AAAAACL/10w="
                }
                // {
                //   id: "e226bc04-0cd6-e811-af11-000d3a32031a",
                //   number: null,
                //   type: "Custom",
                //   lineItems: 9,
                //   owner: "Joe Smith",
                //   created: null,
                //   modified: "2018-10-22T15:21:55.971984Z",
                //   modifiedBy: "Joe Smith",
                //   warehouse: null,
                //   priority: null,
                //   account: {
                //     id: "fe2e733a-0906-416c-bb64-eecab0e6dcb3",
                //     name: "Joe's Tavern",
                //     number: "5558219"
                //   },
                //   name: "Coffee Bar",
                //   locked: false,
                //   canUnlock: true,
                //   private: true,
                //   version: "AAAAACQiNSE="
                // }
              ];
              return of(new HttpResponse({ status: 200, body: guideLegacy }));
            }

            // get order legacy
            if (
              request.url.endsWith("/orders-legacy") &&
              request.method === "GET"
            ) {
              const orderLegacy = {
                id: "99adbfc4-8fbb-e811-af11-000d3a30a3ba",
                version: "AAAAAElojH0=",
                number: "10039",
                accountId: "244cc9ff-b9b4-4889-ba0a-9430ea9c0d72",
                total: 200.0,
                items: 6,
                pieces: 27,
                weight: 531.85,
                shipDate: "2018-10-02",
                memo: null,
                purchaseOrder: null,
                instructions: null,
                dropCodeId: null,
                dropCode: null,
                dropCodeDescription: null,
                dropCodeDisplay: " - ",
                status: "Draft",
                statusReason: null,
                rejectedMessage: null,
                source: "FSA Connect",
                owner: "Billings Tester",
                createdBy: "Billings Tester",
                updatedBy: "Billings Tester",
                submittedBy: "System",
                created: "2018-09-18T22:11:19.9878985Z",
                updated: "2018-09-18T22:11:19.7691423Z",
                submitted: null,
                account: {
                  id: "244cc9ff-b9b4-4889-ba0a-9430ea9c0d72",
                  name: "ABC Food",
                  number: "9992658",
                  creditHold: false
                },
                profitAnalysis: {
                  caseEquivalentQuantity: 27.0,
                  grossProfit: 0,
                  grossProfitPercent: 0,
                  profitPerCaseEquivalent: 0,
                  nextProfitTier: 1.0,
                  amountToNextProfitTier: 0.88
                },
                productStatuses: null,
                missingCriticalItems: null,
                submitOverridesHasErrors: null
              };
              return of(new HttpResponse({ status: 200, body: orderLegacy }));
            }

            // get orders detail legacy
            if (
              request.url.endsWith("/orders-detail-legacy") &&
              request.method === "GET"
            ) {
              const orderDetailLegacy = [
                {
                  id: "04adbfc4-8fbb-e811-af11-000d3a30a3bb",
                  version: "AAAAAElojH8=",
                  orderId: "02adbfc4-8fbb-e811-af11-000d3a30a3ba",
                  productId: "0765cda6-34a1-4a17-b2f0-a53400190e8d",
                  price: 20.0,
                  priceCode: null,
                  quantity: 2,
                  caseEquivalentQuantity: 2.0,
                  shippedQuantity: null,
                  brokenCase: false,
                  grossProfit: 0,
                  grossProfitPercent: 0,
                  cuttingInstructions1Id: null,
                  cuttingInstructions2Id: null,
                  cuttingInstructions3Id: null,
                  specialMessage: null,
                  isPrintSpecialMessage: false,
                  specialPriceCode: null,
                  temporaryOverride: false,
                  permanentOverride: false,
                  sequence: 1,
                  updatedBy: "Billings Tester",
                  updated: "2018-09-18T22:11:21.1717022Z",
                  pricebook: 6235,
                  product: {
                    id: "0765cda6-34a1-4a17-b2f0-a53400190e8d",
                    number: "120892",
                    name: "FLATBREAD 12X5 RUSTIC OVAL",
                    description:
                      "RUSTIC OVAL FLATBREAD WITH HAND MADE APPEARANCE.",
                    brand: "RICH",
                    classNumber: " 62",
                    fsaBranded: false,
                    breakCase: false,
                    pack: 48,
                    size: "4.8Z",
                    packSize: "48/4.8Z",
                    weight: 16.44,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/120892",
                    authorized: true,
                    deactivated: false,
                    suspended: false,
                    orderable: true,
                    orderableMessage: null,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Freeze", display: "Freeze" }],
                    pricing: {
                      productId: "0765cda6-34a1-4a17-b2f0-a53400190e8d",
                      casePrice: 47.0,
                      priceCode: "W",
                      priceCodeDescription: "W - Zone Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 108,
                      specialPriceCode: null
                    },
                    salesData: {
                      id: "00000000-0000-0000-0000-000000000000",
                      number: null,
                      pricing: {
                        caseCost: 45.0,
                        eachCost: null,
                        caseGrossProfit: 1.05,
                        caseGrossProfitPercent: 0.0794237138441156988297637448,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: false,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 44.69,
                        starCasePrice3: 48.76,
                        starCasePrice5: 55.39,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 48.2374,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: {
                        code: "I",
                        caseAmount: 0.63,
                        eachAmount: null
                      },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  id: "04adbfc4-8fbb-e811-af11-000d3a30a3ba",
                  version: "AAAAAElojH8=",
                  orderId: "02adbfc4-8fbb-e811-af11-000d3a30a3ba",
                  productId: "ab8e1834-58a2-4bb6-b54c-3650c02eadcd",
                  price: 40.0,
                  priceCode: null,
                  quantity: 2,
                  caseEquivalentQuantity: 2.0,
                  shippedQuantity: null,
                  brokenCase: false,
                  grossProfit: 0,
                  grossProfitPercent: 0,
                  cuttingInstructions1Id: null,
                  cuttingInstructions2Id: null,
                  cuttingInstructions3Id: null,
                  specialMessage: null,
                  isPrintSpecialMessage: false,
                  specialPriceCode: null,
                  temporaryOverride: false,
                  permanentOverride: false,
                  sequence: 1,
                  updatedBy: "Billings Tester",
                  updated: "2018-09-18T22:11:21.1717022Z",
                  pricebook: 7620,
                  product: {
                    id: "ab8e1834-58a2-4bb6-b54c-3650c02eadcd",
                    number: "118162",
                    name: "SCRUBBER 1.75Z STAINLESS STEEL",
                    description:
                      "1.75 OZ HIGH QUALITY STAINLESS STEEL SCRUBBER, CONTINUOS WIRE CONSTRUCTION FOR TOUGH CLEANING CHORES. PRODUCT OF CHINA.",
                    brand: "PROPAK O",
                    fsaBranded: true,
                    classNumber: " 76",
                    breakCase: false,
                    pack: 1,
                    size: "12CT",
                    packSize: "1/12CT",
                    weight: 1.75,
                    averageWeight: null,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: null,
                    authorized: true,
                    restricted: false,
                    deactivated: false,
                    orderable: true,
                    orderableMessage: null,
                    suspended: false,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Dry", display: "Dry" }],
                    pricing: {
                      productId: "ab8e1834-58a2-4bb6-b54c-3650c02eadcd",
                      productNumber: "118162",
                      casePrice: 40.0,
                      priceCode: "L",
                      priceCodeDescription: "L - Customer PB/Class Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 166,
                      specialPriceCode: null
                    },
                    salesData: {
                      productId: "ab8e1834-58a2-4bb6-b54c-3650c02eadcd",
                      pricing: {
                        caseCost: 40.0,
                        eachCost: null,
                        caseGrossProfit: 0,
                        caseGrossProfitPercent: 0,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: true,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 40.0,
                        starCasePrice3: 40.0,
                        starCasePrice5: 40.0,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 40.0,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: {
                        code: "I",
                        caseAmount: 0.07,
                        eachAmount: null
                      },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  id: "06adbfc4-8fbb-e811-af11-000d3a30a3ba",
                  version: "AAAAAElojIA=",
                  orderId: "02adbfc4-8fbb-e811-af11-000d3a30a3ba",
                  productId: "42dd5337-c3a7-4f09-bd2d-4ddbf1ce4197",
                  price: 40.0,
                  priceCode: null,
                  quantity: 1,
                  caseEquivalentQuantity: 1.0,
                  shippedQuantity: null,
                  brokenCase: false,
                  grossProfit: 0,
                  grossProfitPercent: 0,
                  cuttingInstructions1Id: null,
                  cuttingInstructions2Id: null,
                  cuttingInstructions3Id: null,
                  specialMessage: null,
                  isPrintSpecialMessage: false,
                  specialPriceCode: null,
                  temporaryOverride: false,
                  permanentOverride: false,
                  sequence: 2,
                  updatedBy: "Billings Tester",
                  updated: "2018-09-18T22:11:23.5030213Z",
                  pricebook: 7630,
                  product: {
                    id: "42dd5337-c3a7-4f09-bd2d-4ddbf1ce4197",
                    number: "874722",
                    name: "BLEACH LIQUID ULTRA GERMICIDAL",
                    description:
                      "HOSPITAL GRADE 6% GERMICIDAL LIQUID BLEACH. SDS AVAILABLE ON FSAFOOD.COM REPLACES FSA 498734",
                    brand: "PROPOWER",
                    fsaBranded: true,
                    classNumber: " 76",
                    breakCase: false,
                    pack: 6,
                    size: "121Z",
                    packSize: "6/121Z",
                    weight: 61.1,
                    averageWeight: null,
                    nonStock: "Ship Upon Receipt",
                    nonStockMessage: "SPOKANE SKIPDAY / DATE TUES FLWG WEEK",
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/874722",
                    authorized: true,
                    restricted: false,
                    deactivated: false,
                    orderable: true,
                    orderableMessage: null,
                    suspended: false,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [
                      { name: "NonGMO", display: "Non GMO" },
                      { name: "Dry", display: "Dry" }
                    ],
                    pricing: {
                      productId: "42dd5337-c3a7-4f09-bd2d-4ddbf1ce4197",
                      productNumber: "874722",
                      casePrice: 40.0,
                      priceCode: "L",
                      priceCodeDescription: "L - Customer PB/Class Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 0,
                      specialPriceCode: null
                    },
                    salesData: {
                      productId: "42dd5337-c3a7-4f09-bd2d-4ddbf1ce4197",
                      pricing: {
                        caseCost: 40.0,
                        eachCost: null,
                        caseGrossProfit: 0,
                        caseGrossProfitPercent: 0,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: true,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 40.0,
                        starCasePrice3: 40.0,
                        starCasePrice5: 40.0,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 40.0,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: { code: "I", caseAmount: 2.6, eachAmount: null },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  id: "08adbfc4-8fbb-e811-af11-000d3a30a3ba",
                  version: "AAAAAElojIE=",
                  orderId: "02adbfc4-8fbb-e811-af11-000d3a30a3ba",
                  productId: "543aba06-506f-4d1e-8d3f-728582f4e841",
                  price: 40.0,
                  priceCode: null,
                  quantity: 5,
                  caseEquivalentQuantity: 5.0,
                  shippedQuantity: null,
                  brokenCase: false,
                  grossProfit: 0,
                  grossProfitPercent: 0,
                  cuttingInstructions1Id: null,
                  cuttingInstructions2Id: null,
                  cuttingInstructions3Id: null,
                  specialMessage: null,
                  isPrintSpecialMessage: false,
                  specialPriceCode: null,
                  temporaryOverride: false,
                  permanentOverride: false,
                  sequence: 3,
                  updatedBy: "Billings Tester",
                  updated: "2018-09-18T22:11:27.2738551Z",
                  pricebook: 7630,
                  product: {
                    id: "543aba06-506f-4d1e-8d3f-728582f4e841",
                    number: "445975",
                    name: "CLEANER GRIDDLE QUICK CLEAN LIQUID",
                    description:
                      "LIQUID GRIDDLE CLEANER, QUART BTL. CLEANS FLAT GRIDDLES AT 325 DEG., SAFE ON FOOD CONTACT SURFACES.NO CHEMICAL ODOR. NO CAUSTIC SODA.USE WITH #405 PAD HLDR,#46 GRILL PAD,#410 SQUEEGEE. SDS AVAILABLE ON FSAFOOD.COM",
                    brand: "SCOTCH-BRITE",
                    fsaBranded: false,
                    classNumber: " 76",
                    breakCase: false,
                    pack: 4,
                    size: "32Z",
                    packSize: "4/32Z",
                    weight: 12.01,
                    averageWeight: null,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/445975",
                    authorized: true,
                    restricted: false,
                    deactivated: false,
                    orderable: true,
                    orderableMessage: null,
                    suspended: false,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Dry", display: "Dry" }],
                    pricing: {
                      productId: "543aba06-506f-4d1e-8d3f-728582f4e841",
                      productNumber: "445975",
                      casePrice: 40.0,
                      priceCode: "L",
                      priceCodeDescription: "L - Customer PB/Class Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 82,
                      specialPriceCode: null
                    },
                    salesData: {
                      productId: "543aba06-506f-4d1e-8d3f-728582f4e841",
                      pricing: {
                        caseCost: 40.0,
                        eachCost: null,
                        caseGrossProfit: 0,
                        caseGrossProfitPercent: 0,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: true,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 40.0,
                        starCasePrice3: 40.0,
                        starCasePrice5: 40.0,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 40.0,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: {
                        code: "I",
                        caseAmount: 0.51,
                        eachAmount: null
                      },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  id: "0aadbfc4-8fbb-e811-af11-000d3a30a3ba",
                  version: "AAAAAElojII=",
                  orderId: "02adbfc4-8fbb-e811-af11-000d3a30a3ba",
                  productId: "4b442663-9ad6-49ba-8980-2d9bc0346a0d",
                  price: 40.0,
                  priceCode: null,
                  quantity: 8,
                  caseEquivalentQuantity: 8.0,
                  shippedQuantity: null,
                  brokenCase: false,
                  grossProfit: 0,
                  grossProfitPercent: 0,
                  cuttingInstructions1Id: null,
                  cuttingInstructions2Id: null,
                  cuttingInstructions3Id: null,
                  specialMessage: null,
                  isPrintSpecialMessage: false,
                  specialPriceCode: null,
                  temporaryOverride: false,
                  permanentOverride: false,
                  sequence: 4,
                  updatedBy: "Billings Tester",
                  updated: "2018-09-18T22:11:29.5081832Z",
                  pricebook: 7630,
                  product: {
                    id: "4b442663-9ad6-49ba-8980-2d9bc0346a0d",
                    number: "287320",
                    name: "SANITIZER FOAM INSTANT",
                    description:
                      "USE W/DISPENSER MFG# 2720-12E FSA# 287307, MFG# 2421-DS / FSA #424613 OR MFG# 2424-DS / FSA #2937. PUMPS OUT .8MIL W/EACH USE. SDS AVAILABLE ON FSAFOOD.COM",
                    brand: "PURELL",
                    fsaBranded: false,
                    classNumber: " 76",
                    breakCase: false,
                    pack: 2,
                    size: "1.2LTR",
                    packSize: "2/1.2LTR",
                    weight: 6.0,
                    averageWeight: null,
                    nonStock: "Ship Upon Receipt",
                    nonStockMessage: "R3 TRUCK-MON DATE/TUES & THURS 5PM CUTOF",
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/287320",
                    authorized: true,
                    restricted: false,
                    deactivated: false,
                    orderable: true,
                    orderableMessage: null,
                    suspended: false,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [{ name: "Hazmat", display: "Hazmat" }],
                    pricing: {
                      productId: "4b442663-9ad6-49ba-8980-2d9bc0346a0d",
                      productNumber: "287320",
                      casePrice: 40.0,
                      priceCode: "L",
                      priceCodeDescription: "L - Customer PB/Class Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 0,
                      specialPriceCode: null
                    },
                    salesData: {
                      productId: "4b442663-9ad6-49ba-8980-2d9bc0346a0d",
                      pricing: {
                        caseCost: 40.0,
                        eachCost: null,
                        caseGrossProfit: 0,
                        caseGrossProfitPercent: 0,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: true,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 40.0,
                        starCasePrice3: 40.0,
                        starCasePrice5: 40.0,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 40.0,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: {
                        code: "I",
                        caseAmount: 0.27,
                        eachAmount: null
                      },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  id: "2e837bcb-8fbb-e811-af11-000d3a30a3ba",
                  version: "AAAAAElojIM=",
                  orderId: "02adbfc4-8fbb-e811-af11-000d3a30a3ba",
                  productId: "164cfb45-1096-48d2-af58-0f90fa69b0b1",
                  price: 40.0,
                  priceCode: null,
                  quantity: 7,
                  caseEquivalentQuantity: 7.0,
                  shippedQuantity: null,
                  brokenCase: false,
                  grossProfit: 0,
                  grossProfitPercent: 0,
                  cuttingInstructions1Id: null,
                  cuttingInstructions2Id: null,
                  cuttingInstructions3Id: null,
                  specialMessage: null,
                  isPrintSpecialMessage: false,
                  specialPriceCode: null,
                  temporaryOverride: false,
                  permanentOverride: false,
                  sequence: 5,
                  updatedBy: "Billings Tester",
                  updated: "2018-09-18T22:11:31.3162523Z",
                  pricebook: 7630,
                  product: {
                    id: "164cfb45-1096-48d2-af58-0f90fa69b0b1",
                    number: "778384",
                    name: "SANITIZER QUAT OASIS 146",
                    description:
                      "DISINFECTANT, SANITIZER, DEODORIZER, ONE STEP CLEANER/DISINFECTANT FOR INSTITUTIONAL AND INDUSTRIAL USE. SDS AVAILABLE ON FSAFOOD.COM",
                    brand: "ECOLAB",
                    fsaBranded: false,
                    classNumber: " 76",
                    breakCase: false,
                    pack: 1,
                    size: "2.5GAL",
                    packSize: "1/2.5GAL",
                    weight: 22.0,
                    averageWeight: null,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/778384",
                    authorized: true,
                    restricted: false,
                    deactivated: false,
                    orderable: true,
                    orderableMessage: null,
                    suspended: false,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [
                      { name: "Kosher", display: "Kosher" },
                      { name: "Dry", display: "Dry" }
                    ],
                    pricing: {
                      productId: "164cfb45-1096-48d2-af58-0f90fa69b0b1",
                      productNumber: "778384",
                      casePrice: 40.0,
                      priceCode: "L",
                      priceCodeDescription: "L - Customer PB/Class Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 38,
                      specialPriceCode: null
                    },
                    salesData: {
                      productId: "164cfb45-1096-48d2-af58-0f90fa69b0b1",
                      pricing: {
                        caseCost: 40.0,
                        eachCost: null,
                        caseGrossProfit: 0,
                        caseGrossProfitPercent: 0,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: true,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 40.0,
                        starCasePrice3: 40.0,
                        starCasePrice5: 40.0,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 40.0,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: {
                        code: "I",
                        caseAmount: 0.94,
                        eachAmount: null
                      },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                },
                {
                  id: "30837bcb-8fbb-e811-af11-000d3a30a3ba",
                  version: "AAAAAElojIQ=",
                  orderId: "02adbfc4-8fbb-e811-af11-000d3a30a3ba",
                  productId: "1b7f8b00-c0c8-4682-879b-b01922ba3b69",
                  price: 40.0,
                  priceCode: null,
                  quantity: 4,
                  caseEquivalentQuantity: 4.0,
                  shippedQuantity: null,
                  brokenCase: false,
                  grossProfit: 0,
                  grossProfitPercent: 0,
                  cuttingInstructions1Id: null,
                  cuttingInstructions2Id: null,
                  cuttingInstructions3Id: null,
                  specialMessage: null,
                  isPrintSpecialMessage: false,
                  specialPriceCode: null,
                  temporaryOverride: false,
                  permanentOverride: false,
                  sequence: 6,
                  updatedBy: "Billings Tester",
                  updated: "2018-09-18T22:11:32.7850183Z",
                  pricebook: 7630,
                  product: {
                    id: "1b7f8b00-c0c8-4682-879b-b01922ba3b69",
                    number: "656585",
                    name: "SANITIZER ULTRA SAN LOW TEMPERATURE",
                    description:
                      "ENERGY EFFICIENT DISHMACHINE SANITIZER.  FAST-ACTING, STABLE FORMULA ENSURES OPTIMUM RESULTS AND PROLONGS SHELF LIFE.  EPA REGISTERED. SDS AVAILABLE ON FSAFOOD.COM",
                    brand: "ECOLAB",
                    fsaBranded: false,
                    classNumber: " 76",
                    breakCase: false,
                    pack: 1,
                    size: "5GAL",
                    packSize: "1/5GAL",
                    weight: 51.3,
                    averageWeight: null,
                    nonStock: null,
                    nonStockMessage: null,
                    groupPurchasing: null,
                    randomWeight: false,
                    proprietary: false,
                    imageUrl: "https://cxp-cdn.azureedge.net/cards/656585",
                    authorized: true,
                    restricted: false,
                    deactivated: false,
                    orderable: true,
                    orderableMessage: null,
                    suspended: false,
                    proprietaryToAnotherAccount: false,
                    tags: [],
                    badges: [
                      { name: "Kosher", display: "Kosher" },
                      { name: "Hazmat", display: "Hazmat" }
                    ],
                    pricing: {
                      productId: "1b7f8b00-c0c8-4682-879b-b01922ba3b69",
                      productNumber: "656585",
                      casePrice: 40.0,
                      priceCode: "L",
                      priceCodeDescription: "L - Customer PB/Class Override",
                      eachPrice: null,
                      eachPriceCode: null,
                      eachPriceCodeDescription: null,
                      quantityOnHand: 33,
                      specialPriceCode: null
                    },
                    salesData: {
                      productId: "1b7f8b00-c0c8-4682-879b-b01922ba3b69",
                      pricing: {
                        caseCost: 40.0,
                        eachCost: null,
                        caseGrossProfit: 0,
                        caseGrossProfitPercent: 0,
                        eachGrossProfit: null,
                        eachGrossProfitPercent: null,
                        isCaseOverride: true,
                        isEachOverride: false,
                        canOverride: true,
                        isDeviated: false,
                        lastInvoiceCasePrice: null,
                        lastInvoiceCaseQuantity: null,
                        lastInvoiceEachPrice: null,
                        lastInvoiceEachQuantity: null,
                        autoApplySpecialPriceCode: null,
                        starCasePrice1: 40.0,
                        starCasePrice3: 40.0,
                        starCasePrice5: 40.0,
                        starEachPrice1: null,
                        starEachPrice3: null,
                        starEachPrice5: null,
                        caseOverrideThreshold: 40.0,
                        eachOverrideThreshold: null,
                        flyerPrices: []
                      },
                      freight: {
                        code: "I",
                        caseAmount: 2.31,
                        eachAmount: null
                      },
                      caseHistory: null,
                      eachHistory: null
                    },
                    featured: false,
                    critical: false
                  }
                }
              ];
              return of(
                new HttpResponse({ status: 200, body: orderDetailLegacy })
              );
            }

            // get orders
            if (request.url.endsWith("/orders") && request.method === "GET") {
              const orders = [
                {
                  id: "o1",
                  name: "Tom's Order",
                  lineItems: [
                    {
                      lid: "li1",
                      pid: "p1",
                      qtyEach: 3
                    },
                    {
                      lid: "li3",
                      pid: "p3",
                      qtyCase: 1
                    }
                  ]
                },
                {
                  id: "o2",
                  name: "Stephanie's Order",
                  lineItems: [
                    {
                      lid: "li3",
                      pid: "p3",
                      qtyEach: 3
                    },
                    {
                      lid: "li4",
                      pid: "p4",
                      qtyEach: 3
                    }
                  ]
                }
              ];
              return of(new HttpResponse({ status: 200, body: orders }));
            }

            // add order
            if (
              request.url.endsWith("/orders/add") &&
              request.method === "POST"
            ) {
              request.body.id = new Date().getUTCMilliseconds().toString();
              // respond 200 OK
              return of(new HttpResponse({ status: 200, body: request.body }));
            }

            // update quantity
            if (
              request.url.endsWith("/order-detail/update") &&
              request.method === "POST"
            ) {
              const detail = {
                id: "test",
                ...request.body
              };
              // respond 200 OK
              return of(new HttpResponse({ status: 200, body: detail }));
            }

            //all calls to work that aren't handeled
            return next.handle(request);
          })
        )

        //delay the response
        .pipe(materialize())
        .pipe(delay(1500))
        .pipe(dematerialize())
    );
  }
}

export let fakeServerProvider = {
  provide: HTTP_INTERCEPTORS,
  useClass: FakeServerInterceptor,
  multi: true
};
